
import calculadora.sobre;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author renato
 */
public class Calc extends javax.swing.JFrame {
    
    char operacao;
    String temp,numanterior,copiar;
    double num1,num2,resultado;

    public Calc() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtpainel = new javax.swing.JTextPane();
        btbsp = new javax.swing.JButton();
        bt7 = new javax.swing.JButton();
        bt4 = new javax.swing.JButton();
        bt1 = new javax.swing.JButton();
        bt0 = new javax.swing.JButton();
        btce = new javax.swing.JButton();
        bt8 = new javax.swing.JButton();
        bt5 = new javax.swing.JButton();
        bt2 = new javax.swing.JButton();
        btponto = new javax.swing.JButton();
        btctr = new javax.swing.JButton();
        bt9 = new javax.swing.JButton();
        bt6 = new javax.swing.JButton();
        bt3 = new javax.swing.JButton();
        btigual = new javax.swing.JButton();
        bttrocar = new javax.swing.JButton();
        btdivisao = new javax.swing.JButton();
        btmultiplicacao = new javax.swing.JButton();
        btsubtracao = new javax.swing.JButton();
        btsoma = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Calculadora");

        jScrollPane1.setViewportView(txtpainel);

        btbsp.setText("Bsp");
        btbsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btbspActionPerformed(evt);
            }
        });

        bt7.setText("7");
        bt7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt7ActionPerformed(evt);
            }
        });

        bt4.setText("4");
        bt4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt4ActionPerformed(evt);
            }
        });

        bt1.setText("1");
        bt1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt1ActionPerformed(evt);
            }
        });

        bt0.setText("0");
        bt0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt0ActionPerformed(evt);
            }
        });

        btce.setText("CE");
        btce.setToolTipText("Limpar");
        btce.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btceActionPerformed(evt);
            }
        });

        bt8.setText("8");
        bt8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt8ActionPerformed(evt);
            }
        });

        bt5.setText("5");
        bt5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt5ActionPerformed(evt);
            }
        });

        bt2.setText("2");
        bt2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt2ActionPerformed(evt);
            }
        });

        btponto.setText(".");
        btponto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btpontoActionPerformed(evt);
            }
        });

        btctr.setText("Ctr");
        btctr.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btctrActionPerformed(evt);
            }
        });

        bt9.setText("9");
        bt9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt9ActionPerformed(evt);
            }
        });

        bt6.setText("6");
        bt6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt6ActionPerformed(evt);
            }
        });

        bt3.setText("3");
        bt3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt3ActionPerformed(evt);
            }
        });

        btigual.setText("=");
        btigual.setToolTipText("Igual");
        btigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btigualActionPerformed(evt);
            }
        });

        bttrocar.setText("-+");
        bttrocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bttrocarActionPerformed(evt);
            }
        });

        btdivisao.setText("/");
        btdivisao.setToolTipText("Divisão");
        btdivisao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btdivisaoActionPerformed(evt);
            }
        });

        btmultiplicacao.setText("*");
        btmultiplicacao.setToolTipText("Multiplicação");
        btmultiplicacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmultiplicacaoActionPerformed(evt);
            }
        });

        btsubtracao.setText("-");
        btsubtracao.setToolTipText("Subtração");
        btsubtracao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsubtracaoActionPerformed(evt);
            }
        });

        btsoma.setText("+");
        btsoma.setToolTipText("Soma");
        btsoma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btsomaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt7)
                            .addGap(18, 18, 18)
                            .addComponent(bt8)
                            .addGap(18, 18, 18)
                            .addComponent(bt9)
                            .addGap(18, 18, 18)
                            .addComponent(btdivisao))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt4)
                            .addGap(18, 18, 18)
                            .addComponent(bt5)
                            .addGap(18, 18, 18)
                            .addComponent(bt6)
                            .addGap(18, 18, 18)
                            .addComponent(btmultiplicacao))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt1)
                            .addGap(18, 18, 18)
                            .addComponent(bt2)
                            .addGap(18, 18, 18)
                            .addComponent(bt3)
                            .addGap(18, 18, 18)
                            .addComponent(btsubtracao))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btbsp)
                            .addGap(18, 18, 18)
                            .addComponent(btce)
                            .addGap(18, 18, 18)
                            .addComponent(btctr)
                            .addGap(18, 18, 18)
                            .addComponent(bttrocar))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(bt0)
                            .addGap(18, 18, 18)
                            .addComponent(btponto)
                            .addGap(18, 18, 18)
                            .addComponent(btigual)
                            .addGap(18, 18, 18)
                            .addComponent(btsoma))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {bt0, bt1, bt2, bt3, bt4, bt5, bt6, bt7, bt8, bt9, btbsp, btce, btctr, btdivisao, btigual, btmultiplicacao, btponto, btsoma, btsubtracao, bttrocar});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btbsp)
                    .addComponent(btce)
                    .addComponent(btctr)
                    .addComponent(bttrocar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt7)
                    .addComponent(bt8)
                    .addComponent(bt9)
                    .addComponent(btdivisao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt4)
                    .addComponent(bt5)
                    .addComponent(bt6)
                    .addComponent(btmultiplicacao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt1)
                    .addComponent(bt2)
                    .addComponent(bt3)
                    .addComponent(btsubtracao))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bt0)
                    .addComponent(btponto)
                    .addComponent(btigual)
                    .addComponent(btsoma))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jMenu1.setMnemonic('e');
        jMenu1.setText("Editar");

        jMenuItem2.setMnemonic('c');
        jMenuItem2.setText("Copiar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setMnemonic('v');
        jMenuItem3.setText("Colar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenuBar1.add(jMenu1);

        jMenu2.setMnemonic('s');
        jMenu2.setText("Sobre");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });

        jMenuItem4.setMnemonic('w');
        jMenuItem4.setText("Sobre");
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setMnemonic('a');
        jMenu3.setText("Sair");
        jMenu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu3MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu3);

        jMenu4.setMnemonic('c');
        jMenu4.setText("Calculadora");

        jMenuItem1.setMnemonic('s');
        jMenuItem1.setText("Sair");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bt0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt0ActionPerformed
        InserirNumeros("0");
    }//GEN-LAST:event_bt0ActionPerformed

    private void InserirNumeros(String numero) {
        temp = txtpainel.getText();
        temp = temp + numero;
        txtpainel.setText(temp);
    }

    private void bt1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt1ActionPerformed
        InserirNumeros("1");
    }//GEN-LAST:event_bt1ActionPerformed

    private void btpontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btpontoActionPerformed
        InserirNumeros("."); 
    }//GEN-LAST:event_btpontoActionPerformed

    private void bt2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt2ActionPerformed
        InserirNumeros("2");
    }//GEN-LAST:event_bt2ActionPerformed

    private void bt3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt3ActionPerformed
        InserirNumeros("3");
    }//GEN-LAST:event_bt3ActionPerformed

    private void bt4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt4ActionPerformed
        InserirNumeros("4");
    }//GEN-LAST:event_bt4ActionPerformed

    private void bt5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt5ActionPerformed
        InserirNumeros("5");
    }//GEN-LAST:event_bt5ActionPerformed

    private void bt6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt6ActionPerformed
        InserirNumeros("6");
    }//GEN-LAST:event_bt6ActionPerformed

    private void bt7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt7ActionPerformed
        InserirNumeros("7");
    }//GEN-LAST:event_bt7ActionPerformed

    private void bt8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt8ActionPerformed
        InserirNumeros("8");
    }//GEN-LAST:event_bt8ActionPerformed

    private void bt9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bt9ActionPerformed
        InserirNumeros("9");
    }//GEN-LAST:event_bt9ActionPerformed

    private void btsomaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsomaActionPerformed
        ResultadoOperacao('+');
    }//GEN-LAST:event_btsomaActionPerformed

    private void ResultadoOperacao(char op) throws NumberFormatException {
        operacao = op;
        num1 = Double.parseDouble(txtpainel.getText());
        txtpainel.setText("");
    }

    private void btigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btigualActionPerformed
        num2 = Double.parseDouble(txtpainel.getText());
        
        switch(operacao){
            
            case '+':
                resultado = num1 + num2;
                break;
                
            case '-':
                resultado = num1 - num2;
                break;
                
            case '*':
                resultado = num1 * num2;
                break;
                
            case '/':
                resultado = num1 / num2;
                break;
        }
        txtpainel.setText(String.valueOf(resultado));
    }//GEN-LAST:event_btigualActionPerformed

    private void btsubtracaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btsubtracaoActionPerformed
        ResultadoOperacao('-');
    }//GEN-LAST:event_btsubtracaoActionPerformed

    private void btmultiplicacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmultiplicacaoActionPerformed
        ResultadoOperacao('*');
    }//GEN-LAST:event_btmultiplicacaoActionPerformed

    private void btdivisaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btdivisaoActionPerformed
        ResultadoOperacao('/');
    }//GEN-LAST:event_btdivisaoActionPerformed

    private void btctrActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btctrActionPerformed
        num2 = 0;
        txtpainel.setText(String.valueOf(num1));
    }//GEN-LAST:event_btctrActionPerformed

    private void btceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btceActionPerformed
        num1 = 0;
        num2 = 0;
        txtpainel.setText("");
    }//GEN-LAST:event_btceActionPerformed

    private void btbspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btbspActionPerformed
        temp = numanterior;
        txtpainel.setText(temp);
    }//GEN-LAST:event_btbspActionPerformed

    private void bttrocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bttrocarActionPerformed
        if(temp.startsWith("-")){
            temp = temp.replace('-', '+');
        }else if(temp.startsWith("+")){
            temp = temp.replace('+', '-');
        }else{
            temp = "-" + temp;
        }
        txtpainel.setText(temp);
    }//GEN-LAST:event_bttrocarActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu3MouseClicked
        System.exit(0);
    }//GEN-LAST:event_jMenu3MouseClicked

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        copiar = txtpainel.getText();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
       txtpainel.setText(copiar);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        new sobre().show();
    }//GEN-LAST:event_jMenu2MouseClicked

    /**
     * @param args the command line arguments 
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bt0;
    private javax.swing.JButton bt1;
    private javax.swing.JButton bt2;
    private javax.swing.JButton bt3;
    private javax.swing.JButton bt4;
    private javax.swing.JButton bt5;
    private javax.swing.JButton bt6;
    private javax.swing.JButton bt7;
    private javax.swing.JButton bt8;
    private javax.swing.JButton bt9;
    private javax.swing.JButton btbsp;
    private javax.swing.JButton btce;
    private javax.swing.JButton btctr;
    private javax.swing.JButton btdivisao;
    private javax.swing.JButton btigual;
    private javax.swing.JButton btmultiplicacao;
    private javax.swing.JButton btponto;
    private javax.swing.JButton btsoma;
    private javax.swing.JButton btsubtracao;
    private javax.swing.JButton bttrocar;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextPane txtpainel;
    // End of variables declaration//GEN-END:variables
}
